### ISSUE TITLE
Question: cant see advanced service provider

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [WangDaYeeeeee/GeometricWeather#376] opened 2022-07-21 21:18 UTC
So on v3.011_gplay i cant see this setting to out in my OpenWeatherMap API key.

On v3.102_fdroid i can see this setting.

Is this correct?

If this is correct could u maybe give an estimate when the app in the gplay store is going to get updates?

**Comment by papjul** [comment] 2022-07-22 05:17
If you already updated to v3.102_fdroid, you're done, you have no update to expect from Google Play. On the next update, you can download it from here or let it update from Google Play (this will be the _gplay version). Currently, v3.10X are beta updates only distributed through the beta channel.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2022-07-22 06:39
@papjul when do you plan to release the latest version on gplay?

**Comment by papjul** [comment] 2022-07-22 07:09
It is released on Google Play as a beta release, in the beta channel. You can update either by switching to the beta channel or from the releases page of GitHub.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2022-07-22 07:14
How do i switch to the beta channel? i couldn't find it.

**Comment by papjul** [comment] 2022-07-22 07:22
I don't use Google Play on my device so I can't guide you but there should be an option to join the beta program from the main page of the app on the Google Play Store. If you can't find it, updating to v3.102_gplay from the releases page of GitHub will result in the exact same version as the one distributed through the beta channel of Google Play.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2022-07-22 07:53
Thankyou! When will it go out of beta on gplay?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2022-07-22 11:28
@papjul u have to enable beta in gplay. Current users from gplay cannot use your application in beta.

Other applications have this message being displayed on the bottom of the screen

![Screenshot_20220722-132428.png](https://user-images.githubusercontent.com/73130443/180429991-55d4d231-dd1c-4b30-a561-bae0a234eaed.png)

Your app doesnt have that

![Screenshot_20220722-132458.png](https://user-images.githubusercontent.com/73130443/180430029-ed7617ee-4b84-42f0-997b-f8e868881344.png)

**Comment by papjul** [comment] 2022-07-22 11:35
I don't manage releases on Google Play Store but your request sounds like a duplicate of #362

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2022-07-22 15:44
Ok so u dont know when u will do a next release on gplay?

**Comment by papjul** [comment] 2022-07-22 16:06
I don't do the releases, I'm a contributor and I just try to help the users on the issues if I can.

**Closed as completed** 2022-07-22 19:22 UTC
