### ISSUE TITLE
cannot get the data of weather

### ISSUE THREAD

**Issue by losky2987** [WangDaYeeeeee/GeometricWeather#469] opened 2023-03-11 09:08 UTC
since today morning, i can't get the weather data via geometricweather, i try to change the source, but not work.

**Comment by losky2987** [comment] 2023-03-11 09:14
oppo reno5 pro plus with android 13
i use the latest release, gplay version

**Comment by JayXT** [comment] 2023-03-11 09:57
I have the same issue (Pixel 6a, Android 13).

**Comment by papjul** [comment] 2023-03-11 10:15
Can't reproduce (I’m using a development branch).

> i try to change the source, but not work.

What providers did you try? Please check at the bottom of the screen the text "Powered by XXXX" to be sure you indeed added a location with the new source.
I would be surprised if all providers don't work at the same time (OpenWeatherMap requires a v2.5 API key, if you want to use it, so just try with others).

**Comment by JayXT** [comment] 2023-03-11 10:22
I use the default accuweather.com provider. All advanced service provider settings aren't changed, they are set to defaults. Nothing has changed in terms of configuration too. Yesterday the app worked, today it stopped. After pulling to refresh the data, I'm getting "Request weather data failed" error in the bottom popup.

![image](https://user-images.githubusercontent.com/8045344/224478916-16fd63d6-42f7-4c2d-8753-420617090654.png)

At the bottom of the screen I have "* Powered by accuweather.com".

**Comment by pacjo** [comment] 2023-03-11 10:48
I can also confirm the issue. 

Provider: AccuWeather
Device: Redmi Note 10 Pro (sweet)
OS: Spark (A13), security patch: 5 February 2023

App downloaded from fdroid (3.102_fdroid)

**Comment by giwrgosmant** [comment] 2023-03-11 11:13
I can confirm too.

**Comment by papjul** [comment] 2023-03-11 11:22
Can one of you retry with a fresh install of the APK artifact from this page?
`https://github.com/WangDaYeeeeee/GeometricWeather/pull/440/checks`

Because I can get weather from AccuWeather for the city of Lviv on this version, with no issue.
If it works, we will need to make a new release from it.

**Comment by JayXT** [comment] 2023-03-11 11:33
I don't have opportunity to install it right now, but it's worth mentioning that the behavior isn't limited to Lviv city. I've added New York too and the result for it hasn't changed.

**Comment by losky2987** [comment] 2023-03-11 11:33
> Can one of you retry with a fresh install of the APK artifact from this page? `https://github.com/WangDaYeeeeee/GeometricWeather/pull/440/checks`
> 
> Because I can get weather from AccuWeather for the city of Lviv on this version, with no issue. If it works, we will need to make a new release from it.

good news: i installed your version, and it's work as before, so i think we need a new version in Release. thanks for your work

**Comment by losky2987** [comment] 2023-03-11 11:47
still a question for this project: do you know why WangDaYe since April 2021 is no longer update the Release package? I see that in Dev branch he is still updating commits but not building new Release.

**Comment by papjul** [comment] 2023-03-11 12:00
> still a question for this project: do you know why WangDaYe since April 2021 is no longer update the Release package? I see that in Dev branch he is still updating commits but not building new Release.

No, I don't. I got no answer from his email, and he is not commenting on issues neither, unfortunately.
As you said, he is still a bit active on commits, so I believe he is still interested in his project but lacks free time.

Let's give him a few days to make a release, otherwise I will check with the F-Droid guys if they can (temporarily) switch to my fork. However, I can't make a new Google Play or Cool APK release.

**Comment by JayXT** [comment] 2023-03-11 14:43
In my case the problem resolved by itself. I wonder what was the root-cause...

**Comment by nach0** [comment] 2023-03-11 16:29
Same as @JayXT. Had this issue, I checked again after reading that comment and AccuWeather is working again

**Comment by papjul** [comment] 2023-03-11 17:24
> In my case the problem resolved by itself. I wonder what was the root-cause...

Probably `null` values sent by AccuWeather that weren't safely checked in current version ;)

**Comment by breversa** [comment] 2023-03-14 19:49
> `https://github.com/WangDaYeeeeee/GeometricWeather/pull/440/checks`

This version works (again) for me as well. Will it stay compatible with F-Droid updates?

**Comment by papjul** [comment] 2023-03-14 21:11
> > `https://github.com/WangDaYeeeeee/GeometricWeather/pull/440/checks`
> 
> This version works (again) for me as well. Will it stay compatible with F-Droid updates?

No, GitHub actions don't have the same signature as F-Droid, you need to uninstall each time you want to switch to one version or the other ;)

**Comment by pacjo** [comment] 2023-03-18 20:27
As the fdroid version of Geometric Weather (`3.102_fdroid`) is once again working with Accuweather, I think it's safe to close this issue. @losky2987 ?

**Comment by losky2987** [comment] 2023-03-18 20:46
> As the fdroid version of Geometric Weather (`3.102_fdroid`) is once again working with Accuweather, I think it's safe to close this issue. @losky2987 ?
yes, if you want, but i'm not sure if close this issue it's good for someone who has the same problem. I think if we keep this issue open, when somebody needs help, man can get the information for the temporary solution

**Comment by pacjo** [comment] 2023-03-18 20:52
I'm not associated with this project in any way, so I can't close it. Even then it will still be visible in the closed issues (so just a bit harder to find).

**Closed as completed** 2024-03-08 12:54 UTC
